# Generated by Django 2.2.28 on 2022-07-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='basketuser',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='basket_unique_user_recipe'),
        ),
    ]
