version: '3.9'
services:

  backend:
    image: jony2024/foodgram:latest
    restart: always
    volumes:
      - static-files:/vol/web  
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env

  nginx:
    image: jony2024/foodgram_nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static-files:/vol/static
    depends_on:
      - backend

  frontend:
    image: jony2024/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - nginx

volumes:
  postgres-data:
  static-files: